version: "3.8"

services:

  airflow-webserver:
    env_file:
      - ./_docker/dev-airflow.cfg.env
    environment:
      - AIRFLOW_CONN_S3CONN=s3://s3/?host=http://localstack:4572&aws_access_key_id=abc&aws_secret_access_key=123
      - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://airflow/logs
    depends_on:
      - postgres
      - redis
      - localstack

  airflow-scheduler:
    env_file:
      - ./_docker/dev-airflow.cfg.env
    environment:
      - AIRFLOW_CONN_S3CONN=s3://s3/?host=http://localstack:4572&aws_access_key_id=abc&aws_secret_access_key=123
      - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://airflow/logs

  airflow-worker:
    env_file:
      - ./_docker/dev-airflow.cfg.env
    environment:
      - AIRFLOW_CONN_S3CONN=s3://s3/?host=http://localstack:4572&aws_access_key_id=abc&aws_secret_access_key=123
      - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://airflow/logs

  postgres:
    image: postgres:12-alpine
    env_file:
      - ./_docker/dev-airflow.cfg.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${LOCAL_PATH_POSTGRES}:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    env_file:
      - ./_docker/dev-airflow.cfg.env
    volumes:
      - ${LOCAL_PATH_REDIS}:/data
    ports:
      - 6379:6379
    command: redis-server --requirepass redispass

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3:4572
      - DEFAULT_REGION=us-west-2
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - ${LOCAL_PATH_LOCALSTACK}:/tmp/localstack/data
      - ./_docker:/docker-entrypoint-initaws.d
    ports:
      - 4572:4572
