FROM python:3.7-slim

WORKDIR /pricepluscost

COPY ./pricepluscost ./pricepluscost
COPY .env .
COPY requirements.txt .
COPY setup.py .

RUN ["/usr/local/bin/python","-m","pip","install","--upgrade","pip"]

RUN ["pip","install","-r","requirements.txt"]

CMD ["bash"]